language: php
php:
  - '5.6'
  - '7.0'

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
